### ISSUE TITLE
Image download slows down rendering

### ISSUE THREAD

**Issue by Magellol** [cestbones/cestbones.github.io#1]
Hey there 👋 

Not sure if you guys have noticed but the rendering process is being slowed down when the image starts downloading. We've gotta fix it, it's awful UX. Amazon said things about sites being too slow, affecting business results.

I'm not too knowledgeable about images. I've checked on SO and people suggest to do the following.

```tsx
import 'react';
```

I can provide a PR.

**Comment by kirillzakharov** [comment]
What is exactly `react`?. Can you elaborate?

**Comment by lukechesser** [comment]
@Magellol please see the rules on contributing. This repo is written in coffeescript. Gotta drop the `;`

**Comment by Magellol** [comment]
Sorry, I should have read it.

<img width="1017" alt="screen shot 2018-04-25 at 9 01 39 pm" src="https://user-images.githubusercontent.com/3819093/39280205-e115b5be-48cb-11e8-810e-55ceb0719e16.png">

I feel this project lacks of JavaScript.

**Comment by Magellol** [comment]
See #3 which addresses some of it. Closing.
